package ar.edu.unsta.robotteam.mate;

import java.awt.BorderLayout;
import java.awt.Point;

/**
 *
 * @author gustavo
 */
public class SimuladorBrazoMain extends javax.swing.JFrame {

    private ModeloBrazo m_modelo;
    private Lienzo m_lienzo;

    /**
     * Creates new form SimuladorBrazoMain
     */
    public SimuladorBrazoMain() {
        initComponents();
        m_modelo = new ModeloBrazo();

        ui_sldBC.setMaximum((int) m_modelo.getBCMax());
        ui_sldBC.setMinimum((int) m_modelo.getBCMin());
        ui_sldGH.setMaximum((int) m_modelo.getGHMax());
        ui_sldGH.setMinimum((int) m_modelo.getGHMin());
        
        ui_sldBC.setValue((ui_sldBC.getMinimum() + ui_sldBC.getMaximum())/2);
        ui_sldGH.setValue((ui_sldGH.getMinimum() + ui_sldGH.getMaximum())/2);
        
        m_lienzo = new Lienzo();
        m_lienzo.setModeloAPantalla(0.8);
        m_lienzo.setOrigenPantalla(new Point(800, 500));
        ui_ContenedorLienzo.add(m_lienzo, BorderLayout.CENTER);

        redibuja();

    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ui_sldBC = new javax.swing.JSlider();
        ui_sldGH = new javax.swing.JSlider();
        ui_ContenedorLienzo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel1.setText("SIMULADOR DE BRAZO v1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        jLabel2.setText("BC:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setText("GH:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        ui_sldBC.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ui_sldBCStateChanged(evt);
            }
        });
        jPanel1.add(ui_sldBC, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        ui_sldGH.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                ui_sldGHStateChanged(evt);
            }
        });
        jPanel1.add(ui_sldGH, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        ui_ContenedorLienzo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        ui_ContenedorLienzo.setLayout(new java.awt.BorderLayout());
        getContentPane().add(ui_ContenedorLienzo, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(952, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ui_sldBCStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ui_sldBCStateChanged

        double l_BC = ui_sldBC.getValue();
        m_modelo.setBC(l_BC);
        redibuja();
    }//GEN-LAST:event_ui_sldBCStateChanged

    private void ui_sldGHStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_ui_sldGHStateChanged
        double l_GH = ui_sldGH.getValue();
        m_modelo.setGH(l_GH);

        redibuja();
    }//GEN-LAST:event_ui_sldGHStateChanged

    private void redibuja() {

        m_modelo.recalcula();
        if (m_lienzo == null) {
            return;
        } // end if
        m_lienzo.setDibujables(m_modelo.getDibujables());

        ui_ContenedorLienzo.updateUI();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimuladorBrazoMain.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimuladorBrazoMain.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimuladorBrazoMain.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimuladorBrazoMain.class.
                    getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimuladorBrazoMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel ui_ContenedorLienzo;
    private javax.swing.JSlider ui_sldBC;
    private javax.swing.JSlider ui_sldGH;
    // End of variables declaration//GEN-END:variables
}
